[project]
name = "my-project"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "numpy>=2.0.2",
    "pandas>=2.3.0",
    "requests>=2.32.4",
]

[tool.uv]
dev-dependencies = [
    "pytest",
    "black",
    "numpy>=2.0.2",
    "pandas>=2.3.0",
]
